name: DDHub
author: TriiNoxYs
version: 1.0
main: fr.triinoxys.ddhub
commands:
  chat:
    description: Activer ou desactiver le chat
  clearchat:
    description: Vider le chat
  bypass:
    description: Acceder au perms vanilla du serveur
  spawn:
    description: Se teleporter au spawn
  setspawn:
    description: Defenir le spawn
  reloadconfig:
    description: Recharger la config
  ping:
    description: Affiche votre ping ou celui d'un autre joueur